### ISSUE TITLE
Anmeldedaten aller Nutzer einsehbar

### ISSUE THREAD

**Issue by exmatrikulator** [lugfl/Northern-LUG-camp-website#13]
Es ist möglich die Anmeldedaten der anderen Nutzer ohne Authentifizierung zu sehen.

`for i in $(seq 1 260); do wget "https://www.lug-camp-2017.de/index.php?p=60&anmeldung=$i" -O  anmeldung$i.html; done`

**Comment by jan-lugfl** [comment]
Sollte gleich beim nächsten Live update gefixed sein...
Hab noch ein Problem mehr gefunden..
